In [ ]:
import pandas as pd

In [ ]:
datos_viviendas = pd.read_csv("/content/drive/MyDrive/AnaliticaPython/alquileres_viviendas.csv", sep = ";")

In [ ]:
datos_viviendas.head(30)

,Unnamed: 0,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
2,2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
3,3,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
4,4,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
5,5,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0
6,6,Casa en condominio,Ate,5,4,5,750,22000.0,NaN,NaN
7,7,Casa en condominio,El Agustino,2,2,0,65,1000.0,NaN,NaN
8,8,Departamento,Pachacámac,1,0,0,36,1200.0,NaN,NaN
9,9,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0
10,10,Departamento,San Borja,3,1,1,90,1500.0,455.0,14.0
11,11,Departamento,San Borja,1,0,1,40,2000.0,561.0,50.0
12,12,Habitación,San Borja,1,0,0,27,1800.0,501.0,NaN
13,13,Departamento,San Borja,4,3,1,243,13000.0,2000.0,803.0
14,14,Flat,Chorrillos,3,1,1,80,3800.0,1040.0,NaN
15,15,Casa en condominio,San Luis,3,1,1,115,2000.0,NaN,NaN
16,16,Departamento,Callao,3,0,0,54,950.0,300.0,28.0
17,17,Departamento,Ate,2,1,1,67,1700.0,589.0,147.0
18,18,Departamento,San Miguel,2,1,0,110,1900.0,700.0,138.0
19,19,Casa en condominio,Ate,4,3,2,466,7500.0,2695.0,NaN
20,20,Departamento,Santa Rosa,3,1,0,68,1000.0,670.0,NaN
21,21,Departamento,San Miguel,2,1,0,78,2000.0,700.0,NaN
22,22,Flat,Rímac,1,0,0,56,4500.0,1900.0,1500.0
23,23,Departamento,Comas,3,1,1,125,7000.0,2100.0,463.0
24,24,Departamento,San Miguel,1,0,0,48,750.0,772.0,25.0
25,25,Departamento,Ate,3,3,1,175,4200.0,1500.0,500.0
26,26,Casa,Lince,4,1,2,400,12000.0,NaN,NaN
27,27,Departamento,Chorrillos,2,1,0,76,2500.0,740.0,NaN
28,28,Departamento,San Borja,3,1,2,378,10000.0,2150.0,700.0
29,29,Departamento,San Borja,3,0,0,180,5500.0,1780.0,420.0

In [ ]:
sel_departamento = datos_viviendas["Tipo"] == "Departamento"
cant_departamento = datos_viviendas[sel_departamento].shape[0]
cant_departamento

19532

In [ ]:
sel_otros_departamento = datos_viviendas["Tipo"] == "Departamento"
cant_otras = datos_viviendas[~sel_otros_departamento].shape[0]
cant_otras

3658

In [ ]:
sel_casa_hab_coch = (datos_viviendas["Tipo"] == "Casa") | (datos_viviendas["Tipo"] == "Habitación") | (datos_viviendas["Tipo"] == "Cochera")
cant_casa_hab_coch = datos_viviendas[sel_casa_hab_coch].shape[0]
cant_casa_hab_coch

1885

In [1]:
sel_area = (datos_viviendas['Area']>=60) & (datos_viviendas['Area']<=100)
cant_viv_area = datos_viviendas[sel_area]
cant_viv_area

NameError: ignored

In [ ]:
sel_area = (datos_viviendas['Area']>=60) & (datos_viviendas['Area']<=100)
cant_viv_area = datos_viviendas[sel_area].shape[0]
cant_viv_area

8990

In [ ]:
sel_hab_precio = (datos_viviendas['Cuartos']>=4) & (datos_viviendas['Valor']<=2000)
cant_hab_precio = datos_viviendas[sel_hab_precio].shape[0]
cant_hab_precio

62

In [ ]:
print("Se encontraron los siguentes resultados:")
print(f"La cantidad de departamentos es de {cant_departamento}")
print(f"La cantidad de otras viviendas {cant_otras}")
print(f"La cantidad de viviendas tipo Casa, habitación y cochera es de {cant_casa_hab_coch}")
print(f"La cantidad de viviendas con un área de 60 y 100 metros cuadrados es de {cant_viv_area}")
print(f"La cantidad de vivendas con mas de 4 habitaciones y un valor menor o igual a 2000 reales es de{cant_hab_precio}")

Se encontraron los siguentes resultados:
La cantidad de departamentos es de 19532
La cantidad de otras viviendas 3658
La cantidad de viviendas tipo Casa, habitación y cochera es de 1885
La cantidad de viviendas con un área de 60 y 100 metros cuadrados es de 8990
La cantidad de vivendas con mas de 4 habitaciones y un valor menor o igual a 2000 reales es de62

In [ ]:
datos_viviendas.isnull()

,Unnamed: 0,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...
23185,False,False,False,False,False,False,False,False,True,True
23186,False,False,False,False,False,False,False,False,False,False
23187,False,False,False,False,False,False,False,False,False,False
23188,False,False,False,False,False,False,False,False,False,False
23189,False,False,False,False,False,False,False,False,False,True

In [ ]:
datos_viviendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23190 entries, 0 to 23189
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     23190 non-null  int64
 1   Tipo           23190 non-null  object
 2   Distrito       23190 non-null  object
 3   Cuartos        23190 non-null  int64
 4   Vacantes       23190 non-null  int64
 5   Suites         23190 non-null  int64
 6   Area           23190 non-null  int64
 7   Valor          23181 non-null  float64
 8   Mantenimiento  21265 non-null  float64
 9   Impuesto       16254 non-null  float64
dtypes: float64(3), int64(5), object(2)
memory usage: 1.8+ MB

In [ ]:
datos_viviendas[datos_viviendas['Valor'].isnull()]

,Unnamed: 0,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
60,60,Departamento,Ate,2,1,1,70,NaN,970.0,68.0
1533,1533,Departamento,San Bartolo,2,0,0,75,NaN,878.0,NaN
1727,1727,Casa,Lince,3,4,3,363,NaN,NaN,NaN
2065,2065,Departamento,Chorrillos,2,0,0,95,NaN,1010.0,170.0
2087,2087,Departamento,San Borja,2,0,0,72,NaN,850.0,NaN
5083,5083,Casa,Lince,3,2,1,100,NaN,NaN,NaN
8813,8813,Departamento,San Bartolo,2,0,1,75,NaN,878.0,NaN
9204,9204,Departamento,La Punta,3,0,1,135,NaN,910.0,228.0
9410,9410,Departamento,La Perla,3,1,1,105,NaN,880.0,221.0

In [ ]:
vivienda_nan = datos_viviendas.shape[0]

In [ ]:
vivienda_nan = datos_viviendas.shape[0]
datos_viviendas.dropna(subset=['Valor'],inplace = True)
vivienda_nan_b = datos_viviendas.shape[0]
vivienda_nan - vivienda_nan_b

9

In [ ]:
datos_viviendas[datos_viviendas['Valor'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, Tipo, Distrito, Cuartos, Vacantes, Suites, Area, Valor, Mantenimiento, Impuesto]
Index: []

#Cuando la desicion es conservar los datos debemos sobre escribir con un valor, en este caso 0, para conservar la fila.

In [ ]:
datos_viviendas[datos_viviendas['Mantenimiento'].isnull()].shape[0]

1923

In [ ]:
sel = (datos_viviendas['Tipo'] == 'Departamento') & (datos_viviendas['Mantenimiento'].isnull())

In [ ]:
sel_A = datos_viviendas.shape[0]
datos_viviendas = datos_viviendas[~sel]
datos_viviendas

,Unnamed: 0,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
2,2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
3,3,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
5,5,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0
...,...,...,...,...,...,...,...,...,...,...
23185,23185,Cochera,Pachacámac,0,0,0,755,14000.0,NaN,NaN
23186,23186,Habitación,Pachacámac,0,0,0,27,800.0,350.0,25.0
23187,23187,Departamento,Lince,3,1,2,78,1800.0,800.0,40.0
23188,23188,Departamento,Rímac,2,1,0,48,1400.0,509.0,37.0
23189,23189,Departamento,Rímac,2,0,0,70,3000.0,760.0,NaN